user-save-interval: 120

speedboat-speed-upgrade-increment: 0.03
speedboat-speed-upgrade-starting-cost: 300.0
speedboat-speed-upgrade-max: 20

fishes-starting-fish-capacity: 30
fishes-upgrade-starting-cost: 500.0
fishes-upgrade-increment: 5
fishes-upgrade-max: 20