user-save-interval: 300

daily-rewards:
  default:
    - "crates give {player} t2 1"
  sub:
    - "crates give {player} t3 1"
    - "collectables set {player} sub"
  sub+:
    - "crates give {player} t4 1"
    - "collectables set {player} sub+"
  sub++:
    - "crates give {player} t5 1"
    - "collectables set {player} sub++"

arena:
  location-1: world:36.54615295468963:44.0:-44.47213113885291:88.82573:-3.048827
  location-2: world:31.2297573899345:44.0:-44.64828779514104:272.52707:4.194084