package me.senseiju.commscraft

private const val PERMISSION_PREFIX = "commscraft."

/*
 * Generic permissions
 */
const val PERMISSION_RELOAD = PERMISSION_PREFIX + "reload"

/*
 * Collectables
 */
const val PERMISSION_COLLECTABLES_PREFIX = PERMISSION_PREFIX + "collectables."

const val PERMISSION_COLLECTABLES_REMOVE = PERMISSION_COLLECTABLES_PREFIX + "remove"
const val PERMISSION_COLLECTABLES_SET = PERMISSION_COLLECTABLES_PREFIX + "set"

/*
 * NPC
 */
const val PERMISSION_NPC_PREFIX = PERMISSION_PREFIX + "npc."

const val PERMISSION_NPC_SPAWN = PERMISSION_NPC_PREFIX + "spawn"
const val PERMISSION_NPC_REMOVE = PERMISSION_NPC_PREFIX + "remove"

/*
 * Speedboats
 */
const val PERMISSION_SPEEDBOAT_PREFIX = PERMISSION_PREFIX + "speedboat."

const val PERMISSION_SPEEDBOAT_USE = PERMISSION_SPEEDBOAT_PREFIX + "use"

/*
 * Crates
 */
const val PERMISSION_CRATES_PREFIX = PERMISSION_PREFIX + "crates."

const val PERMISSION_CRATES_GIVE = PERMISSION_CRATES_PREFIX + "give"

/*
 * Models
 */
const val PERMISSION_MODELS_PREFIX = PERMISSION_PREFIX + "models."

const val PERMISSION_MODELS_TEMP = PERMISSION_MODELS_PREFIX + "temp"
const val PERMISSION_MODELS_REMOVE = PERMISSION_MODELS_PREFIX + "remove"
const val PERMISSION_MODELS_SET = PERMISSION_MODELS_PREFIX + "set"