package me.senseiju.sennetmc

private const val PERMISSION_PREFIX = "sennetmc."

/*
 * Generic permissions
 */
const val PERMISSION_RELOAD = PERMISSION_PREFIX + "reload"

/*
 * Collectables
 */
private const val PERMISSION_COLLECTABLES_PREFIX = PERMISSION_PREFIX + "collectables."

const val PERMISSION_COLLECTABLES_REMOVE = PERMISSION_COLLECTABLES_PREFIX + "remove"
const val PERMISSION_COLLECTABLES_SET = PERMISSION_COLLECTABLES_PREFIX + "set"

/*
 * NPC
 */
private const val PERMISSION_NPC_PREFIX = PERMISSION_PREFIX + "npc."

const val PERMISSION_NPC_SPAWN = PERMISSION_NPC_PREFIX + "spawn"
const val PERMISSION_NPC_REMOVE = PERMISSION_NPC_PREFIX + "remove"

const val PERMISSION_NPC_CAPTAIN_SET_SPAWN_POINT = PERMISSION_NPC_SPAWN + "setspawnpoint"

/*
 * Speedboats
 */
private const val PERMISSION_SPEEDBOAT_PREFIX = PERMISSION_PREFIX + "speedboat."

const val PERMISSION_SPEEDBOAT_USE = PERMISSION_SPEEDBOAT_PREFIX + "use"

/*
 * Crates
 */
private const val PERMISSION_CRATES_PREFIX = PERMISSION_PREFIX + "crates."

const val PERMISSION_CRATES_GIVE = PERMISSION_CRATES_PREFIX + "give"

/*
 * Events
 */
private const val PERMISSION_EVENTS_PREFIX = PERMISSION_PREFIX + "events."

const val PERMISSION_EVENTS_START = PERMISSION_EVENTS_PREFIX + "start"

/*
 * Arena
 */
private const val PERMISSION_ARENA_PREFIX = PERMISSION_PREFIX + "arena."

const val PERMISSION_ARENA_SET_LOCATION = PERMISSION_ARENA_PREFIX + "setlocation"

/*
 * Commands
 */
private const val PERMISSION_COMMANDS_PREFIX = PERMISSION_PREFIX + "commands."

const val PERMISSION_COMMANDS_FISHMONGER = PERMISSION_COMMANDS_PREFIX + "fishmonger"
const val PERMISSION_COMMANDS_LOOTER = PERMISSION_COMMANDS_PREFIX + "looter"
const val PERMISSION_COMMANDS_SELL = PERMISSION_COMMANDS_PREFIX + "sell"

/*
 * Scrap
 */
private const val PERMISSION_SCRAP_PREFIX = PERMISSION_PREFIX + "scrap."

const val PERMISSION_SCRAP_GIVE = PERMISSION_SCRAP_PREFIX + "give"

/*
 * Equipment
 */
private const val PERMISSION_COMMANDS_EQUIPMENT = PERMISSION_PREFIX + "equipment."

const val PERMISSION_EQUIPMENT_GIVE = PERMISSION_COMMANDS_EQUIPMENT + "give"